/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model.view;

import java.awt.Color;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import model.bean.Campeonato;
import model.bean.Jogador;
import model.bean.Time;
import model.dao.JogadorDAO;

/**
 *
 * @author guilherme
 */
public class TelaJogadores extends javax.swing.JFrame {

    Campeonato camp;
    Time time;
    Border bordaVermelha = BorderFactory.createLineBorder(Color.RED);
    Border bordaNormal;

    /**
     * Creates new form TelaJogadores
     *
     * @param camp
     * @param time
     */
    public TelaJogadores(Campeonato camp, Time time) { // parâmetro 
        initComponents();
        bordaNormal = txtNome.getBorder();
        this.camp = camp;
        this.time = time;
        lblTime.setText(time.getNome()); // nome do time que ta sendo cadastrado, pro cara não se perder
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApelido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        btnEncerrar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        lblTime = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Jogadores");
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Time:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 30, 40, 20);

        txtNome.setBackground(new java.awt.Color(126, 217, 87));
        txtNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtNome.setBorder(null);
        getContentPane().add(txtNome);
        txtNome.setBounds(190, 160, 180, 15);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apelido:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 220, 70, 17);

        txtApelido.setBackground(new java.awt.Color(126, 217, 87));
        txtApelido.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtApelido.setBorder(null);
        getContentPane().add(txtApelido);
        txtApelido.setBounds(190, 220, 180, 15);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Data Nasc. :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 280, 110, 20);

        txtDocumento.setBackground(new java.awt.Color(126, 217, 87));
        txtDocumento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDocumento.setBorder(null);
        getContentPane().add(txtDocumento);
        txtDocumento.setBounds(210, 280, 160, 15);

        btnEncerrar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEncerrar.setText("Encerrar");
        btnEncerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEncerrar);
        btnEncerrar.setBounds(340, 420, 80, 31);

        btnCadastrar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(60, 420, 110, 31);

        lblTime.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblTime);
        lblTime.setBounds(60, 30, 130, 20);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 30, 60, 0);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nome:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(100, 160, 60, 17);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(210, 300, 160, 10);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(190, 180, 180, 10);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(190, 240, 180, 10);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/view/6.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 500, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        txtNome.setBorder(bordaNormal);
        txtApelido.setBorder(bordaNormal);
        txtDocumento.setBorder(bordaNormal);
        if (txtNome.getText().equals("") || txtApelido.getText().equals("") || txtDocumento.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Verifique os campos em branco");
            if (txtNome.getText().equals("")) {
                txtNome.setBorder(bordaVermelha);
            }
            if (txtApelido.getText().equals("")) {
                txtApelido.setBorder(bordaVermelha);
            }
            if (txtDocumento.getText().equals("")) {
                txtDocumento.setBorder(bordaVermelha);
            }
        } else {
            Jogador jogador = new Jogador();
            jogador.setNome(txtNome.getText());
            jogador.setApelido(txtApelido.getText());
            DateFormat sql = new SimpleDateFormat("yyyy-MM-dd");
            Date data = null;
            try {
                data = sql.parse(txtDocumento.getText());
            } catch (ParseException ex) {
                Logger.getLogger(TelaSumula.class.getName()).log(Level.SEVERE, null, ex);
            }
            jogador.setDataNasc((java.sql.Date) data);
            jogador.setTime(time); // pega o time que foi passado lá em cima
            JogadorDAO jogadorDAO = new JogadorDAO();
            jogadorDAO.inserir(jogador);
            txtNome.setBorder(bordaNormal);
            txtApelido.setBorder(bordaNormal);
            txtDocumento.setBorder(bordaNormal);// cadastra o jogador no banco de dados
            txtNome.setText("");
            txtApelido.setText("");
            txtDocumento.setText("");

        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnEncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncerrarActionPerformed
        TelaCadastroTime tct = new TelaCadastroTime(camp);
        tct.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEncerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJogadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJogadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJogadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJogadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //      new TelaJogadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEncerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblTime;
    private javax.swing.JTextField txtApelido;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
