/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model.view;


import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import model.bean.Campeonato;
import model.bean.Jogador;
import model.bean.Time;
import model.dao.JogadorDAO;

/**
 *
 * @author Cliente
 */
public class TelaAlteraJogador extends javax.swing.JFrame {

    Campeonato camp;
    Time time;
    Jogador jogador;
    String acao;
    Border borda;
    /**
     * Creates new form TelaAlteraJogador
     */
    public TelaAlteraJogador(Campeonato camp, Time time, Jogador jogador, String acao) {
        initComponents();
        borda = txtNome.getBorder();
        this.camp = camp;
        this.time = time;
        this.jogador = jogador;
        this.acao = acao;
        lblTime.setText(time.getNome());
        if (acao.equals("adicionar")) { // se for pra adicionar um novo ele deixa os campos em branco
            this.setTitle("Adiciona Jogador");
            txtNome.setText("");
            txtApelido.setText("");
            txtDocumento.setText("");
        } else { // se for pra alterar ele coloca os dados do jogador
            this.setTitle("Altera Jogador");
            txtNome.setText(jogador.getNome());
            txtApelido.setText(jogador.getApelido());
            txtDocumento.setText(String.valueOf(jogador.getDocumento()));
            txtDocumento.setEnabled(false); // não pode alterar o número do documento do cara
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApelido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        lblTime = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alterar Jogador");
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        txtNome.setBackground(new java.awt.Color(126, 217, 87));
        txtNome.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtNome.setForeground(new java.awt.Color(255, 255, 255));
        txtNome.setBorder(null);
        getContentPane().add(txtNome);
        txtNome.setBounds(210, 210, 160, 15);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apelido:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 270, 70, 20);

        txtApelido.setBackground(new java.awt.Color(126, 217, 87));
        txtApelido.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtApelido.setForeground(new java.awt.Color(255, 255, 255));
        txtApelido.setBorder(null);
        getContentPane().add(txtApelido);
        txtApelido.setBounds(210, 270, 160, 15);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("N° Documento:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 150, 110, 20);

        txtDocumento.setBackground(new java.awt.Color(126, 217, 87));
        txtDocumento.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtDocumento.setForeground(new java.awt.Color(255, 255, 255));
        txtDocumento.setBorder(null);
        getContentPane().add(txtDocumento);
        txtDocumento.setBounds(210, 150, 160, 15);

        btnSalvar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(60, 420, 80, 23);

        btnVoltar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(340, 420, 80, 23);

        lblTime.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblTime);
        lblTime.setBounds(70, 30, 130, 20);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nome:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(150, 210, 44, 17);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Time:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 30, 37, 17);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(210, 290, 160, 10);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(210, 170, 160, 10);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(210, 230, 160, 10);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/view/7.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        txtNome.setBorder(borda);
        txtApelido.setBorder(borda);
        txtDocumento.setBorder(borda);
        if (txtNome.getText().equals("") || txtApelido.getText().equals("") || txtDocumento.getText().equals("")) {
            Border bordaVermelha = BorderFactory.createLineBorder(Color.RED);
            JOptionPane.showMessageDialog(null, "Por favor, preencha todos os campos");
            if(txtNome.getText().equals("")){
                txtNome.setBorder(bordaVermelha);
            }
            if(txtApelido.getText().equals("")){
                txtApelido.setBorder(bordaVermelha);
            }
            if(txtDocumento.getText().equals("")){
                txtDocumento.setBorder(bordaVermelha);
            }
            
            //verifica se tem coisa em branco e avisa
        } else {
            if (acao.equals("adicionar")) { // se for pra adicionar...
                jogador.setNome(txtNome.getText());
                jogador.setApelido(txtApelido.getText());
                jogador.setDocumento(Integer.valueOf(txtDocumento.getText()));
                jogador.setTime(time);
                JogadorDAO jogadorDAO = new JogadorDAO();
                jogadorDAO.inserir(jogador); //... ele chama o método de adicionar
            }else{ // se for pra alterar...
                jogador.setNome(txtNome.getText());
                jogador.setApelido(txtApelido.getText());
                
                JogadorDAO jogadorDAO = new JogadorDAO();
                jogadorDAO.alterar(jogador); //...chama o método de alterar
            }
            this.dispose();
            TelaEditarTime tet = new TelaEditarTime(camp, time);
            tet.setVisible(true);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        TelaEditarTime tet = new TelaEditarTime(camp, time);
        tet.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAlteraJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAlteraJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAlteraJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlteraJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //       new TelaAlteraJogador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblTime;
    private javax.swing.JTextField txtApelido;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
