/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model.view;

import java.awt.Color;
import java.util.List;
import javax.swing.BorderFactory;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

import model.bean.Campeonato;
import model.bean.Time;
import model.dao.CampeonatoDAO;
import model.dao.TimeDAO;

/**
 *
 * @author guilherme
 */
public class TelaEditarCamp extends javax.swing.JFrame {

    Campeonato camp;
    Border bordaVermelha = BorderFactory.createLineBorder(Color.RED);
    Border bordaNormal;

    /**
     * Creates new form TelaEditarCamp
     */
    public TelaEditarCamp(Campeonato camp) {
        initComponents();
        bordaNormal = txtNome.getBorder();
        this.camp = camp;
        txtNome.setText(camp.getNome());
        txtCidade.setText(camp.getLocal());
        txtPremiacao.setText(camp.getPremiacao());
        TimeDAO timeDAO = new TimeDAO();
        DefaultListModel model = (DefaultListModel) lstTimes.getModel();
        List<Time> times = timeDAO.listarPorCamp(camp); // busca os times que fazem parte do campeonato
        for (Time time : times) {
            model.addElement(time);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNome = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstTimes = new javax.swing.JList(new DefaultListModel());
        btnEditarTime = new javax.swing.JButton();
        btnApagarTime = new javax.swing.JButton();
        lblNome1 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblNome2 = new javax.swing.JLabel();
        txtPremiacao = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Editar Campeonato");
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        txtNome.setBackground(new java.awt.Color(126, 217, 87));
        txtNome.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtNome.setForeground(new java.awt.Color(255, 255, 255));
        txtNome.setBorder(null);
        getContentPane().add(txtNome);
        txtNome.setBounds(170, 80, 230, 30);

        btnSalvar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(30, 430, 69, 23);

        btnCancelar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(370, 430, 83, 23);

        lblNome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setText("Nome:");
        getContentPane().add(lblNome);
        lblNome.setBounds(90, 80, 50, 30);

        lstTimes.setBackground(new java.awt.Color(126, 217, 87));
        lstTimes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        lstTimes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lstTimes.setForeground(new java.awt.Color(255, 255, 255));
        lstTimes.setDragEnabled(true);
        lstTimes.setSelectionBackground(new java.awt.Color(0, 153, 0));
        lstTimes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstTimesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstTimes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 130, 310, 150);

        btnEditarTime.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEditarTime.setText("Editar Time");
        btnEditarTime.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarTime.setEnabled(false);
        btnEditarTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarTimeActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditarTime);
        btnEditarTime.setBounds(120, 430, 97, 23);

        btnApagarTime.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnApagarTime.setText("Remover time");
        btnApagarTime.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnApagarTime.setEnabled(false);
        btnApagarTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarTimeActionPerformed(evt);
            }
        });
        getContentPane().add(btnApagarTime);
        btnApagarTime.setBounds(235, 430, 120, 23);

        lblNome1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNome1.setForeground(new java.awt.Color(255, 255, 255));
        lblNome1.setText("Cidade:");
        getContentPane().add(lblNome1);
        lblNome1.setBounds(90, 300, 60, 30);

        txtCidade.setBackground(new java.awt.Color(126, 217, 87));
        txtCidade.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtCidade.setForeground(new java.awt.Color(255, 255, 255));
        txtCidade.setBorder(null);
        getContentPane().add(txtCidade);
        txtCidade.setBounds(170, 300, 220, 30);

        lblNome2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNome2.setForeground(new java.awt.Color(255, 255, 255));
        lblNome2.setText("Premiação:");
        getContentPane().add(lblNome2);
        lblNome2.setBounds(90, 350, 80, 30);

        txtPremiacao.setBackground(new java.awt.Color(126, 217, 87));
        txtPremiacao.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtPremiacao.setForeground(new java.awt.Color(255, 255, 255));
        txtPremiacao.setBorder(null);
        getContentPane().add(txtPremiacao);
        txtPremiacao.setBounds(170, 350, 220, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(170, 380, 220, 10);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(170, 110, 230, 10);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(170, 330, 220, 10);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/view/7.png"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        txtNome.setBorder(bordaNormal);
        txtCidade.setBorder(bordaNormal);
        if (txtNome.getText().equals("") || txtCidade.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Verifique os campos em branco");
            if (txtNome.getText().equals("")) {
                txtNome.setBorder(bordaVermelha);
            }
            if (txtCidade.getText().equals("")) {
                txtCidade.setBorder(bordaVermelha);
            }

        } else {
            CampeonatoDAO campDAO = new CampeonatoDAO();

            camp.setNome(txtNome.getText());
            camp.setLocal(txtCidade.getText());
            camp.setPremiacao(txtPremiacao.getText());
            campDAO.alterar(camp); // troca os dados antigos pelos novos
            TelaCarregarCamp telaCarregarCamp = new TelaCarregarCamp();
            telaCarregarCamp.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
        TelaCarregarCamp telaCarregarCamp = new TelaCarregarCamp();
        telaCarregarCamp.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEditarTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarTimeActionPerformed
        if (lstTimes.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um time");
        } else {
            Time time = (Time) lstTimes.getSelectedValue(); // pega o time selecionado
            this.dispose();
            TelaEditarTime telaEditarTime = new TelaEditarTime(camp, time);
            telaEditarTime.setVisible(true);
        }
    }//GEN-LAST:event_btnEditarTimeActionPerformed

    private void btnApagarTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarTimeActionPerformed
        if (lstTimes.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um time");
        } else {
            if (JOptionPane.showConfirmDialog(null, "Tem certeza?", "Remover Time", JOptionPane.WARNING_MESSAGE) == 0) {
                TimeDAO clubesDAO = new TimeDAO();
                clubesDAO.removerDoCamp((Time) lstTimes.getSelectedValue()); 
                DefaultListModel model = (DefaultListModel) lstTimes.getModel();
                model.remove(lstTimes.getSelectedIndex()); // remove o time da lista
            } else {

            }
        }
    }//GEN-LAST:event_btnApagarTimeActionPerformed

    private void lstTimesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstTimesMouseClicked
        
        int m = lstTimes.getSelectedIndex();
        if (m != -1) { // quando seleciona os botões se habilitam
            btnEditarTime.setEnabled(true);
            btnApagarTime.setEnabled(true);
        }
    }//GEN-LAST:event_lstTimesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEditarCamp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEditarCamp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEditarCamp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEditarCamp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //               new TelaEditarCamp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagarTime;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditarTime;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JLabel lblNome2;
    private javax.swing.JList lstTimes;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPremiacao;
    // End of variables declaration//GEN-END:variables
}
