/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model.view;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import model.bean.Gols;
import model.bean.CAmarelo;
import model.bean.CVermelho;
import model.bean.Partida;
import model.dao.CAmareloDAO;
import model.dao.CVermelhoDAO;
import model.dao.GolsDAO;

/**
 *
 * @author Cliente
 */
public class TelaSumula extends javax.swing.JFrame {
Partida partida;
    /**
     * Creates new form TelaSumula
     * @param partida
     * 
     */
    public TelaSumula(Partida partida) {
        initComponents();
        this.partida=partida;
        lblEstadio.setText(partida.getLocal());
        DateFormat sql = new SimpleDateFormat("yyyy-MM-dd");
        DateFormat normal = new SimpleDateFormat("dd-MM-yyyy");
        Date data= null;
        try {
            data = sql.parse(partida.getData());
        } catch (ParseException ex) {
            Logger.getLogger(TelaSumula.class.getName()).log(Level.SEVERE, null, ex);
        }
        lblData.setText(normal.format(data));
        lblMandante.setText(partida.getMandante().getNome());
        lblVisitante.setText(partida.getVisitante().getNome());
        lblGolsMandante.setText(String.valueOf(partida.getPlacarMandante()));
        lblGolsVisitante.setText(String.valueOf(partida.getPlacarVisitante()));
        if(partida.getPenaltisMandante() !=0 || partida.getPenaltisVisitante()!=0){
            lblPenaltiMandante.setText(String.valueOf(partida.getPenaltisMandante()));
            lblPenaltiVisitante.setText(String.valueOf(partida.getPenaltisVisitante()));
        }else{
            lblPenaltiMandante.setVisible(false);
            lblPenaltiVisitante.setVisible(false);
        }
        GolsDAO golDAO = new GolsDAO();
        CAmareloDAO amareloDAO = new CAmareloDAO();
        CVermelhoDAO vermelhoDAO = new CVermelhoDAO();
        List<Gols> gols = golDAO.listar(partida);
        List<CAmarelo> amarelos = amareloDAO.listar(partida);
        List<CVermelho> vermelhos = vermelhoDAO.listar(partida);
        
        DefaultTableModel modGols = (DefaultTableModel)tbGols.getModel();
        DefaultTableModel modAmarelo = (DefaultTableModel)tbAmarelos.getModel();
        DefaultTableModel modVermelho = (DefaultTableModel)tbVermelhos.getModel();
        
        for(Gols gol : gols){
            modGols.addRow(new Object[]{gol.getJogador().getApelido(),gol.getTime().getNome()});
        }
        for(CAmarelo amarelo:amarelos){
            modAmarelo.addRow(new Object[]{amarelo.getJogador().getApelido(),amarelo.getTime().getNome()});
        }
        for(CVermelho vermelho:vermelhos){
            modVermelho.addRow(new Object[]{vermelho.getJogador().getNome(),vermelho.getTime().getNome()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblEstadio = new javax.swing.JLabel();
        lblMandante = new javax.swing.JLabel();
        lblGolsMandante = new javax.swing.JLabel();
        lblPenaltiMandante = new javax.swing.JLabel();
        lblGolsMandante2 = new javax.swing.JLabel();
        lblPenaltiVisitante = new javax.swing.JLabel();
        lblGolsVisitante = new javax.swing.JLabel();
        lblVisitante = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbGols = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbAmarelos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbVermelhos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(126, 217, 87));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEstadio.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblEstadio.setForeground(new java.awt.Color(255, 255, 255));
        lblEstadio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstadio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel2.add(lblEstadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 160, 20));

        lblMandante.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblMandante.setForeground(new java.awt.Color(255, 255, 255));
        lblMandante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMandante.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel2.add(lblMandante, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 160, 20));

        lblGolsMandante.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblGolsMandante.setForeground(new java.awt.Color(255, 255, 255));
        lblGolsMandante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGolsMandante.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel2.add(lblGolsMandante, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 20, 20));

        lblPenaltiMandante.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblPenaltiMandante.setForeground(new java.awt.Color(255, 255, 255));
        lblPenaltiMandante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPenaltiMandante.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel2.add(lblPenaltiMandante, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 20, 20));

        lblGolsMandante2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblGolsMandante2.setForeground(new java.awt.Color(255, 255, 255));
        lblGolsMandante2.setText("X");
        jPanel2.add(lblGolsMandante2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 10, 20));

        lblPenaltiVisitante.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblPenaltiVisitante.setForeground(new java.awt.Color(255, 255, 255));
        lblPenaltiVisitante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPenaltiVisitante.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel2.add(lblPenaltiVisitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 20, 20));

        lblGolsVisitante.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblGolsVisitante.setForeground(new java.awt.Color(255, 255, 255));
        lblGolsVisitante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGolsVisitante.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel2.add(lblGolsVisitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 20, 20));

        lblVisitante.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblVisitante.setForeground(new java.awt.Color(255, 255, 255));
        lblVisitante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVisitante.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel2.add(lblVisitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 160, 20));

        lblData.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblData.setForeground(new java.awt.Color(255, 255, 255));
        lblData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblData.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel2.add(lblData, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 100, 20));

        tbGols.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jogador", "Time"
            }
        ));
        tbGols.setSelectionBackground(new java.awt.Color(0, 153, 0));
        jScrollPane2.setViewportView(tbGols);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 430, 70));

        tbAmarelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jogador", "Time"
            }
        ));
        tbAmarelos.setSelectionBackground(new java.awt.Color(0, 153, 0));
        jScrollPane3.setViewportView(tbAmarelos);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 430, 70));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cartões Amarelos");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 130, 20));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gols");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 40, 20));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cartões Vermelhos");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 140, -1));

        tbVermelhos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jogador", "Time"
            }
        ));
        tbVermelhos.setSelectionBackground(new java.awt.Color(0, 153, 0));
        jScrollPane1.setViewportView(tbVermelhos);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 430, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/view/7.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 490, 480));

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TelaJogos t = new TelaJogos(partida.getCampeonato());
        t.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSumula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSumula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSumula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSumula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
         //       new TelaSumula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblEstadio;
    private javax.swing.JLabel lblGolsMandante;
    private javax.swing.JLabel lblGolsMandante2;
    private javax.swing.JLabel lblGolsVisitante;
    private javax.swing.JLabel lblMandante;
    private javax.swing.JLabel lblPenaltiMandante;
    private javax.swing.JLabel lblPenaltiVisitante;
    private javax.swing.JLabel lblVisitante;
    private javax.swing.JTable tbAmarelos;
    private javax.swing.JTable tbGols;
    private javax.swing.JTable tbVermelhos;
    // End of variables declaration//GEN-END:variables
}
