/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model.view;

import java.awt.Image;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.util.List;
import javax.swing.ImageIcon;
import model.bean.Campeonato;
import model.bean.Partida;
import model.dao.PartidaDAO;


/**
 *
 * @author Cliente
 */
public class TelaSemi extends javax.swing.JFrame {

    Campeonato camp;

    /**
     * Creates new form TelaSemi
     */
    public TelaSemi(Campeonato camp) {
        initComponents();
        this.camp = camp;
        PartidaDAO partidaDAO = new PartidaDAO();
        List<Partida> partidas = partidaDAO.listarFase(camp, "semi");
        byte[] escudo = partidas.get(0).getMandante().getEscudo();
        InputStream is = new ByteArrayInputStream(escudo);
        Image image = new ImageIcon(escudo).getImage();
        ImageIcon icon = new ImageIcon(image);
        lblEscudoTime1.setIcon(icon);
        lblNomeTime1.setText(partidas.get(0).getMandante().getNome());
        escudo = partidas.get(0).getVisitante().getEscudo();
        is = new ByteArrayInputStream(escudo);
        image = new ImageIcon(escudo).getImage();
        icon = new ImageIcon(image);
        lblEscudoTime2.setIcon(icon);
        lblNomeTime2.setText(partidas.get(0).getVisitante().getNome());
        escudo = partidas.get(1).getMandante().getEscudo();
        is = new ByteArrayInputStream(escudo);
        image = new ImageIcon(escudo).getImage();
        icon = new ImageIcon(image);
        lblEscudoTime3.setIcon(icon);
        lblNomeTime3.setText(partidas.get(1).getMandante().getNome());
        escudo = partidas.get(1).getVisitante().getEscudo();
        is = new ByteArrayInputStream(escudo);
        image = new ImageIcon(escudo).getImage();
        icon = new ImageIcon(image);
        lblEscudoTime4.setIcon(icon);
        lblNomeTime4.setText(partidas.get(1).getVisitante().getNome());
        if (partidas.get(0).isCadastrada()) {
            lblGolsTime1.setText(String.valueOf(partidas.get(0).getPlacarMandante()));
            lblGolsTime2.setText(String.valueOf(partidas.get(0).getPlacarVisitante()));
            if (partidas.get(0).getPenaltisMandante() == 0 && partidas.get(0).getPenaltisVisitante() == 0) {
                lblPenalti1.setVisible(false);
                lblPenalti2.setVisible(false);

            } else {
                lblPenalti1.setText(String.valueOf(partidas.get(0).getPenaltisMandante()));
                lblPenalti2.setText(String.valueOf(partidas.get(0).getPenaltisVisitante()));
            }
        }
        if (partidas.get(1).isCadastrada()) {
            lblGolsTime3.setText(String.valueOf(partidas.get(1).getPlacarMandante()));
            lblGolsTime4.setText(String.valueOf(partidas.get(1).getPlacarVisitante()));
            if (partidas.get(1).getPenaltisMandante() == 0 && partidas.get(1).getPenaltisVisitante() == 0) {
                lblPenalti3.setVisible(false);
                lblPenalti4.setVisible(false);

            } else {
                lblPenalti3.setText(String.valueOf(partidas.get(1).getPenaltisMandante()));
                lblPenalti4.setText(String.valueOf(partidas.get(1).getPenaltisVisitante()));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnArtilheiros = new javax.swing.JButton();
        btnSuspensos = new javax.swing.JButton();
        btnJogos = new javax.swing.JButton();
        lblEscudoTime1 = new javax.swing.JLabel();
        lblNomeTime1 = new javax.swing.JLabel();
        lblGolsTime1 = new javax.swing.JLabel();
        lblPenalti1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblPenalti2 = new javax.swing.JLabel();
        lblGolsTime2 = new javax.swing.JLabel();
        lblEscudoTime2 = new javax.swing.JLabel();
        lblNomeTime2 = new javax.swing.JLabel();
        lblEscudoTime3 = new javax.swing.JLabel();
        lblNomeTime3 = new javax.swing.JLabel();
        lblGolsTime3 = new javax.swing.JLabel();
        lblPenalti3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblPenalti4 = new javax.swing.JLabel();
        lblGolsTime4 = new javax.swing.JLabel();
        lblEscudoTime4 = new javax.swing.JLabel();
        lblNomeTime4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Semifinais");
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(126, 217, 87));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCancelar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, -1, 30));

        btnArtilheiros.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnArtilheiros.setText("Artilheiros");
        btnArtilheiros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnArtilheiros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArtilheirosActionPerformed(evt);
            }
        });
        jPanel1.add(btnArtilheiros, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 100, 30));

        btnSuspensos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSuspensos.setText("Suspensos");
        btnSuspensos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSuspensos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuspensosActionPerformed(evt);
            }
        });
        jPanel1.add(btnSuspensos, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, -1, 30));

        btnJogos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnJogos.setText("Jogos");
        btnJogos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnJogos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJogosActionPerformed(evt);
            }
        });
        jPanel1.add(btnJogos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, -1, 30));

        lblEscudoTime1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblEscudoTime1.setForeground(new java.awt.Color(255, 255, 255));
        lblEscudoTime1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEscudoTime1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(lblEscudoTime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 100, 100));

        lblNomeTime1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNomeTime1.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeTime1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeTime1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(lblNomeTime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 100, 10));

        lblGolsTime1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblGolsTime1.setForeground(new java.awt.Color(255, 255, 255));
        lblGolsTime1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGolsTime1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(lblGolsTime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 40, 40));

        lblPenalti1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPenalti1.setForeground(new java.awt.Color(255, 255, 255));
        lblPenalti1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPenalti1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(lblPenalti1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 18, 20));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("X");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 40, 50));

        lblPenalti2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPenalti2.setForeground(new java.awt.Color(255, 255, 255));
        lblPenalti2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPenalti2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(lblPenalti2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 18, 20));

        lblGolsTime2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblGolsTime2.setForeground(new java.awt.Color(255, 255, 255));
        lblGolsTime2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGolsTime2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(lblGolsTime2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 40, 40));

        lblEscudoTime2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblEscudoTime2.setForeground(new java.awt.Color(255, 255, 255));
        lblEscudoTime2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEscudoTime2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(lblEscudoTime2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 100, 100));

        lblNomeTime2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNomeTime2.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeTime2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeTime2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(lblNomeTime2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 100, 10));

        lblEscudoTime3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblEscudoTime3.setForeground(new java.awt.Color(255, 255, 255));
        lblEscudoTime3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEscudoTime3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(lblEscudoTime3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 100, 100));

        lblNomeTime3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNomeTime3.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeTime3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeTime3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(lblNomeTime3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 100, 10));

        lblGolsTime3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblGolsTime3.setForeground(new java.awt.Color(255, 255, 255));
        lblGolsTime3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGolsTime3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(lblGolsTime3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 40, 40));

        lblPenalti3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPenalti3.setForeground(new java.awt.Color(255, 255, 255));
        lblPenalti3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPenalti3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(lblPenalti3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 18, 20));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("X");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 40, 50));

        lblPenalti4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPenalti4.setForeground(new java.awt.Color(255, 255, 255));
        lblPenalti4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPenalti4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(lblPenalti4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 18, 20));

        lblGolsTime4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblGolsTime4.setForeground(new java.awt.Color(255, 255, 255));
        lblGolsTime4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGolsTime4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(lblGolsTime4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 40, 40));

        lblEscudoTime4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblEscudoTime4.setForeground(new java.awt.Color(255, 255, 255));
        lblEscudoTime4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEscudoTime4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(lblEscudoTime4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 100, 100));

        lblNomeTime4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNomeTime4.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeTime4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeTime4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(lblNomeTime4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 100, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/view/7.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
        TelaCarregarCamp telaCarregarCamp = new TelaCarregarCamp();
        telaCarregarCamp.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnJogosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogosActionPerformed
        TelaJogos t = new TelaJogos(camp);
        t.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnJogosActionPerformed

    private void btnArtilheirosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArtilheirosActionPerformed
        this.dispose();
        TelaArtilheiros telaArtilheiros = new TelaArtilheiros(camp);
        telaArtilheiros.setVisible(true);
    }//GEN-LAST:event_btnArtilheirosActionPerformed

    private void btnSuspensosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuspensosActionPerformed
        this.dispose();
        TelaSuspensos ts = new TelaSuspensos(camp);
        ts.setVisible(true);
    }//GEN-LAST:event_btnSuspensosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSemi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSemi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSemi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSemi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //          new TelaSemi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArtilheiros;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnJogos;
    private javax.swing.JButton btnSuspensos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEscudoTime1;
    private javax.swing.JLabel lblEscudoTime2;
    private javax.swing.JLabel lblEscudoTime3;
    private javax.swing.JLabel lblEscudoTime4;
    private javax.swing.JLabel lblGolsTime1;
    private javax.swing.JLabel lblGolsTime2;
    private javax.swing.JLabel lblGolsTime3;
    private javax.swing.JLabel lblGolsTime4;
    private javax.swing.JLabel lblNomeTime1;
    private javax.swing.JLabel lblNomeTime2;
    private javax.swing.JLabel lblNomeTime3;
    private javax.swing.JLabel lblNomeTime4;
    private javax.swing.JLabel lblPenalti1;
    private javax.swing.JLabel lblPenalti2;
    private javax.swing.JLabel lblPenalti3;
    private javax.swing.JLabel lblPenalti4;
    // End of variables declaration//GEN-END:variables
}
