/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model.view;

import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

import model.bean.Campeonato;
import model.bean.Time;
import model.dao.CampeonatoDAO;
import model.dao.TimeDAO;

/**
 *
 * @author guilherme
 */
public class TelaCarregarCamp extends javax.swing.JFrame {

    Campeonato camp = new Campeonato();

    /**
     * Creates new form TelaCarregarCamp
     */
    public TelaCarregarCamp() {
        initComponents();
        DefaultListModel model = (DefaultListModel) lstCamp.getModel();
        CampeonatoDAO campDAO = new CampeonatoDAO();
        List<Campeonato> campeonatos = campDAO.listar(); //busca todos os campeonatos cadastrados
        for (Campeonato campi : campeonatos) {
            model.addElement(campi); // coloca na lista
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstCamp = new javax.swing.JList(new DefaultListModel());
        btnEditar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Campeonatos Salvos");
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        lstCamp.setBackground(new java.awt.Color(126, 217, 87));
        lstCamp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        lstCamp.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lstCamp.setForeground(new java.awt.Color(255, 255, 255));
        lstCamp.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstCamp.setSelectionBackground(new java.awt.Color(0, 204, 0));
        lstCamp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstCampMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstCamp);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(150, 110, 189, 160);

        btnEditar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar);
        btnEditar.setBounds(30, 400, 86, 35);

        btnAtualizar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAtualizar.setText("Atualizar");
        btnAtualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtualizar.setEnabled(false);
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtualizar);
        btnAtualizar.setBounds(150, 400, 86, 35);

        btnApagar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnApagar.setText("Apagar");
        btnApagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnApagar.setEnabled(false);
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });
        getContentPane().add(btnApagar);
        btnApagar.setBounds(270, 400, 86, 35);

        btnCancelar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(390, 400, 86, 35);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/view/7.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (lstCamp.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um campeonato");
        } else {
            camp = (Campeonato) lstCamp.getSelectedValue();

            this.dispose();

            TelaEditarCamp telaEditarCamp = new TelaEditarCamp(camp); // e manda pra tela de editar
            telaEditarCamp.setVisible(true);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
        TelaPrincipal telaPrincipal = new TelaPrincipal();
        telaPrincipal.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void lstCampMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstCampMouseClicked

        int m = lstCamp.getSelectedIndex();
        if (m != -1) { // quando seleciona um campeonato os botoões ficam habilitados
            btnEditar.setEnabled(true);
            btnApagar.setEnabled(true);
            btnAtualizar.setEnabled(true);
        } else {
            btnEditar.setEnabled(false);
            btnApagar.setEnabled(false);
            btnAtualizar.setEnabled(false);
        }
    }//GEN-LAST:event_lstCampMouseClicked

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        if (lstCamp.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um campeonato");
        } else {
            camp = (Campeonato) lstCamp.getSelectedValue();
            if (camp.isFinalizado()) {
                TelaPremios t = new TelaPremios(camp);
                t.setVisible(true);

            } else {
                TimeDAO timeDAO = new TimeDAO();
                
                // pega o campeonato selecionado
                if (camp.isFaseDeGrupos() == true) { //verifica se ta na fase de grupos
                    if (camp.getNumGrupos() == 2 && camp.getNumTimes() == timeDAO.listarPorCamp(camp).size()) { // abre a tela de acordo com o número de grupos
                        TelaDoisGrupos tdg = new TelaDoisGrupos(camp);
                        tdg.setVisible(true);
                    } else if (camp.getNumGrupos() == 4 && camp.getNumTimes() == timeDAO.listarPorCamp(camp).size()) {
                        TelaQuatroGrupos tqg = new TelaQuatroGrupos(camp); //só essa aqui tem comentário vem nessa
                        tqg.setVisible(true); // na fase de grupos
                    } else if (camp.getNumTimes() != timeDAO.listarPorCamp(camp).size()) {
                        TelaCadastroTime tct = new TelaCadastroTime(camp);
                        tct.setVisible(true);
                    }
                } else { // se n tiver na fase de grupos vem pra cá
                    // busca os times q n estão eliminados
                    if(camp.isOitavas()){
                        TelaOitavas t = new TelaOitavas(camp);
                        t.setVisible(true);
                    }
                    if(camp.isQuartas()){
                        TelaQuartas t = new TelaQuartas(camp);
                        t.setVisible(true);
                    }
                    if(camp.isSemi()){
                        TelaSemi t = new TelaSemi(camp);
                        t.setVisible(true);
                    }
                    if(camp.isFinal()){
                        TelaFinal t= new TelaFinal(camp);
                        t.setVisible(true);
                    }
                }

            }
            this.dispose();
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        if (lstCamp.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um campeonato para excluir");
        } else {
            if (JOptionPane.showConfirmDialog(null, "Tem certeza?", "Excluir Campeonato", JOptionPane.WARNING_MESSAGE) == 0) {
                DefaultListModel model = (DefaultListModel) lstCamp.getModel();
                Campeonato camp = (Campeonato) lstCamp.getSelectedValue();
                model.remove(lstCamp.getSelectedIndex()); // remove da lista

                CampeonatoDAO campDAO = new CampeonatoDAO();
                campDAO.excluir(camp); // remove do banco de dados
            } else {

            }
        }


    }//GEN-LAST:event_btnApagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCarregarCamp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCarregarCamp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCarregarCamp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCarregarCamp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCarregarCamp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstCamp;
    // End of variables declaration//GEN-END:variables
}
