/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model.view;

import java.awt.Color;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

import javax.swing.table.DefaultTableModel;
import model.bean.Campeonato;
import model.bean.Jogador;
import model.bean.Time;
import model.dao.JogadorDAO;
import model.dao.TimeDAO;

/**
 *
 * @author Cliente
 */
public class TelaEditarTime extends javax.swing.JFrame {

    Campeonato camp;
    Time time;
    Border bordaVermelha = BorderFactory.createLineBorder(Color.RED);
    Border bordaNormal;

    /**
     * Creates new form TelaEditarTime
     */
    public TelaEditarTime(Campeonato camp, Time time) {
        initComponents();
        bordaNormal = txtNome.getBorder();
        this.camp = camp;
        this.time = time;
        DefaultTableModel tbm = (DefaultTableModel) tbJogadores.getModel();
        txtNome.setText(time.getNome());
        txtDirigente.setText(time.getDirigente());
        txtCidade.setText(time.getCidade());
        JogadorDAO jogadorDAO = new JogadorDAO();
        List<Jogador> jogadores = jogadorDAO.listarPorTime(time); //lista os jogadores que fazem parte desse time
        for (Jogador jogador : jogadores) {
             DateFormat normal = new SimpleDateFormat("dd-MM-yyyy");
            tbm.addRow(
                    new Object[]{
                        normal.format(jogador.getDataNasc()),
                        jogador.getNome(),
                        jogador.getApelido()
                    }
            );
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbJogadores = new javax.swing.JTable();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        txtDirigente = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        btnAdicionar1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        lblEscudo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Editar Time");
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        tbJogadores.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tbJogadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Documento", "Nome", "Apelido"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbJogadores.setSelectionBackground(new java.awt.Color(0, 153, 0));
        tbJogadores.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbJogadores);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 170, 452, 210);

        btnSalvar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(20, 400, 90, 39);

        btnExcluir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(240, 400, 100, 39);

        btnAlterar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAlterar.setText("Alterar Dados");
        btnAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar);
        btnAlterar.setBounds(360, 400, 110, 39);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cidade:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 130, 60, 17);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Dirigente:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 100, 70, 17);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nome:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 70, 60, 17);

        txtCidade.setBackground(new java.awt.Color(126, 217, 87));
        txtCidade.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtCidade.setForeground(new java.awt.Color(255, 255, 255));
        txtCidade.setBorder(null);
        getContentPane().add(txtCidade);
        txtCidade.setBounds(90, 130, 160, 15);

        txtDirigente.setBackground(new java.awt.Color(126, 217, 87));
        txtDirigente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtDirigente.setForeground(new java.awt.Color(255, 255, 255));
        txtDirigente.setBorder(null);
        getContentPane().add(txtDirigente);
        txtDirigente.setBounds(90, 100, 160, 15);

        txtNome.setBackground(new java.awt.Color(126, 217, 87));
        txtNome.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtNome.setForeground(new java.awt.Color(255, 255, 255));
        txtNome.setBorder(null);
        getContentPane().add(txtNome);
        txtNome.setBounds(90, 70, 160, 15);

        btnAdicionar1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAdicionar1.setText("Adicionar");
        btnAdicionar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdicionar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdicionar1);
        btnAdicionar1.setBounds(130, 400, 90, 39);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(90, 150, 160, 10);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(90, 90, 160, 10);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(90, 120, 160, 10);

        lblEscudo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        getContentPane().add(lblEscudo);
        lblEscudo.setBounds(330, 60, 100, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/view/7.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
String acao;
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        txtNome.setBorder(bordaNormal);
        txtDirigente.setBorder(bordaNormal);
        txtCidade.setBorder(bordaNormal);
        if (txtNome.getText().equals("") || txtDirigente.getText().equals("") || txtCidade.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Verifique os campos em branco");
            if (txtNome.getText().equals("")) {
                txtNome.setBorder(bordaVermelha);
            }
            if (txtDirigente.getText().equals("")) {
                txtDirigente.setBorder(bordaVermelha);
            }
            if (txtCidade.getText().equals("")) {
                txtCidade.setBorder(bordaVermelha);
            }
        } else {
            time.setNome(txtNome.getText());
            time.setDirigente(txtDirigente.getText());
            time.setCidade(txtCidade.getText());
            TimeDAO timeDAO = new TimeDAO();
            timeDAO.alterar(time); //troca os dados antigos pelos novos
            TelaEditarCamp tec = new TelaEditarCamp(camp);
            tec.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (tbJogadores.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um jogador");
        } else {
            if (JOptionPane.showConfirmDialog(null, "Tem certeza?", "Excluir Jogador", JOptionPane.WARNING_MESSAGE) == 0) {
                JogadorDAO jogadorDAO = new JogadorDAO();
                Object documento = tbJogadores.getValueAt(tbJogadores.getSelectedRow(), 0); //pega o documento do jogador selecionado
                int cod = (int) documento; // converte em inteiro
                jogadorDAO.excluir(cod); // exclui o jogador do banco de dados
                DefaultTableModel tbm = (DefaultTableModel) tbJogadores.getModel();
                tbm.removeRow(tbJogadores.getSelectedRow()); //remove da lista
            } else {

            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (tbJogadores.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um jogador");
        } else {
            JogadorDAO jogadorDAO = new JogadorDAO();
            Object documento = tbJogadores.getValueAt(tbJogadores.getSelectedRow(), 0);

            Jogador jogador = jogadorDAO.buscar((int) documento);
            acao = "alterar"; //fala pra outra tela o que é pra fazer
            TelaAlteraJogador taj = new TelaAlteraJogador(camp, time, jogador, acao);
            taj.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnAdicionar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionar1ActionPerformed
        acao = "adicionar";
        Jogador jogador = new Jogador();
        TelaAlteraJogador taj = new TelaAlteraJogador(camp, time, jogador, acao);
        taj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdicionar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEditarTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEditarTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEditarTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEditarTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //             new TelaEditarTime().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar1;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblEscudo;
    private javax.swing.JTable tbJogadores;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtDirigente;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
