/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model.view;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.bean.Campeonato;
import model.bean.Jogador;
import model.bean.Time;
import model.dao.JogadorDAO;
import model.dao.TimeDAO;

/**
 *
 * @author guilherme
 */
public class TelaPendurados extends javax.swing.JFrame {

    Campeonato camp;

    /**
     * Creates new form TelaCartoes
     */
    public TelaPendurados(Campeonato camp) {
        initComponents();
        this.camp = camp;

        DefaultTableModel tbm = (DefaultTableModel) tbPendurados.getModel();
        JogadorDAO jogadorDAO = new JogadorDAO();
        TimeDAO timeDAO = new TimeDAO();
        Time time = new Time();
        List<Jogador> jogadores = jogadorDAO.listarPendurados(camp); // busca todos os jogadores que estão pendurados
        for (Jogador jogador : jogadores) {
            tbm.addRow(
                    new Object[]{
                        jogador.getApelido(),
                        timeDAO.buscar(jogador.getTime().getId()).getNome()
                    });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPendurados = new javax.swing.JTable();
        btnVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pendurados");
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel1.setLayout(null);

        tbPendurados.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tbPendurados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jogador", "Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbPendurados.setSelectionBackground(new java.awt.Color(0, 153, 0));
        tbPendurados.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbPendurados);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(33, 60, 430, 310);

        btnVoltar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(btnVoltar);
        btnVoltar.setBounds(391, 430, 70, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/view/7.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        if (camp.isFaseDeGrupos() == true) {
            if (camp.getNumGrupos() == 2) {
                TelaDoisGrupos tdg = new TelaDoisGrupos(camp);
                tdg.setVisible(true);
            } else if (camp.getNumGrupos() == 4) {
                TelaQuatroGrupos tqg = new TelaQuatroGrupos(camp);
                tqg.setVisible(true);
            } 
        } else {
            if(camp.isOitavas()){
            TelaOitavas t = new TelaOitavas(camp);
            t.setVisible(true);
        }else if(camp.isQuartas()){
            TelaQuartas t = new TelaQuartas(camp);
            t.setVisible(true);
        }else if(camp.isSemi()){
            TelaSemi t = new TelaSemi(camp);
            t.setVisible(true);
        }else if(camp.isFinal()){
            TelaFinal t = new TelaFinal(camp);
            t.setVisible(true);
        }
        }
        this.dispose();

    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPendurados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPendurados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPendurados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPendurados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //               new TelaCartoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbPendurados;
    // End of variables declaration//GEN-END:variables
}
