/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model.view;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.bean.Campeonato;
import model.bean.Jogador;
import model.bean.Time;
import model.dao.JogadorDAO;
import model.dao.TimeDAO;

/**
 *
 * @author Cliente
 */
public class TelaSuspensos extends javax.swing.JFrame {

    Campeonato camp;

    /**
     * Creates new form TelaSuspensos
     */
    public TelaSuspensos(Campeonato camp) {
        initComponents();
        this.camp = camp;

        DefaultTableModel tbm = (DefaultTableModel) tbSuspensos.getModel();
        JogadorDAO jogadorDAO = new JogadorDAO();
        TimeDAO timeDAO = new TimeDAO();
        List<Jogador> jogadores = jogadorDAO.listarSuspensosCamp(camp); // busca todos os jogadores que tão suspensos
        for (Jogador jogador : jogadores) {
            tbm.addRow(
                    new Object[]{
                        jogador.getApelido(), // coloca o apelido
                        timeDAO.buscar(jogador.getTime().getId()).getNome() // e o time que ele joga
                    });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSuspensos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Suspensos");
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(380, 420, 72, 23);

        tbSuspensos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tbSuspensos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jogador", "Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbSuspensos.setSelectionBackground(new java.awt.Color(0, 153, 0));
        tbSuspensos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbSuspensos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(21, 67, 452, 270);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/view/7.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (camp.isFaseDeGrupos() == true) {
            if (camp.getNumGrupos() == 2) {
                TelaDoisGrupos tdg = new TelaDoisGrupos(camp);
                tdg.setVisible(true);
            } else if (camp.getNumGrupos() == 4) {
                TelaQuatroGrupos tqg = new TelaQuatroGrupos(camp);
                tqg.setVisible(true);
            }
        } else {
            if (camp.isOitavas()) {
                TelaOitavas t = new TelaOitavas(camp);
                t.setVisible(true);
            } else if (camp.isQuartas()) {
                TelaQuartas t = new TelaQuartas(camp);
                t.setVisible(true);
            } else if (camp.isSemi()) {
                TelaSemi t = new TelaSemi(camp);
                t.setVisible(true);
            } else if (camp.isFinal()) {
                TelaFinal t = new TelaFinal(camp);
                t.setVisible(true);
            }
        }
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSuspensos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSuspensos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSuspensos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSuspensos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //         new TelaSuspensos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbSuspensos;
    // End of variables declaration//GEN-END:variables
}
