/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model.view;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.bean.Campeonato;
import model.bean.Time;
import model.dao.CampeonatoDAO;
import model.dao.JogadorDAO;
import model.dao.TimeDAO;

/**
 *
 * @author guilherme
 */
public class TelaQuatroGrupos extends javax.swing.JFrame {

    Campeonato camp;

    /**
     * Creates new form TelaAtualizarCamp
     */
    public TelaQuatroGrupos(Campeonato camp) {
        initComponents();
        this.camp = camp;
        DefaultTableModel tbm1 = (DefaultTableModel) tbGrupo1.getModel();
        DefaultTableModel tbm2 = (DefaultTableModel) tbGrupo2.getModel();
        DefaultTableModel tbm3 = (DefaultTableModel) tbGrupo3.getModel();
        DefaultTableModel tbm4 = (DefaultTableModel) tbGrupo4.getModel();
        TimeDAO timeDAO = new TimeDAO();
        if (camp.isIniciado()==false) {
            List<Time> cabecasDeChave = timeDAO.listarCabecasDeChave(camp);
            for (Time time : cabecasDeChave) {
                if (time.getGrupo() == 1) {
                    tbm1.addRow(new Object[]{
                        time.getNome(),
                        time.getPontos()
                    });
                } else if (time.getGrupo() == 2) {
                    tbm2.addRow(new Object[]{
                        time.getNome(),
                        time.getPontos()
                    });
                } else if (time.getGrupo() == 3) {
                    tbm3.addRow(new Object[]{
                        time.getNome(),
                        time.getPontos()
                    });
                } else {
                    tbm4.addRow(new Object[]{
                        time.getNome(),
                        time.getPontos()
                    });
                }
            }
            List<Time> times1 = timeDAO.listarGrupoSemCC(1, camp); // busca os times pelo número do grupo por ordem de pontos
            for (Time time : times1) {// e coloca na tabela
                tbm1.addRow(
                        new Object[]{
                            time.getNome(),
                            time.getPontos()
                        }
                );
            }
            List<Time> times2 = timeDAO.listarGrupoSemCC(2, camp);
            for (Time time : times2) {
                tbm2.addRow(
                        new Object[]{
                            time.getNome(),
                            time.getPontos()
                        }
                );
            }
            List<Time> times3 = timeDAO.listarGrupoSemCC(3, camp);
            for (Time time : times3) {
                tbm3.addRow(
                        new Object[]{
                            time.getNome(),
                            time.getPontos()
                        }
                );
            }
            List<Time> times4 = timeDAO.listarGrupoSemCC(4, camp);
            for (Time time : times4) {
                tbm4.addRow(
                        new Object[]{
                            time.getNome(),
                            time.getPontos()
                        }
                );
            }
        }else{
            List<Time>time1 = timeDAO.listarGrupoComCC(1, camp);
            List<Time>time2 = timeDAO.listarGrupoComCC(2, camp);
            List<Time>time3 = timeDAO.listarGrupoComCC(3, camp);
            List<Time>time4 = timeDAO.listarGrupoComCC(4, camp);
            for(Time time : time1){
                tbm1.addRow(new Object[]{time.getNome(),time.getPontos()});
            }
            for(Time time : time2){
                tbm2.addRow(new Object[]{time.getNome(),time.getPontos()});
            }
            for(Time time : time3){
                tbm3.addRow(new Object[]{time.getNome(),time.getPontos()});
            }
            for(Time time : time4){
                tbm4.addRow(new Object[]{time.getNome(),time.getPontos()});
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbGrupo1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbGrupo3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbGrupo4 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbGrupo2 = new javax.swing.JTable();
        btnArtilheiros = new javax.swing.JButton();
        btnPendurados = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnJogos = new javax.swing.JButton();
        btnSuspensos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fase de Grupos");
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        tbGrupo1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tbGrupo1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Grupo 1", "Pts"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbGrupo1.setSelectionBackground(new java.awt.Color(0, 153, 0));
        tbGrupo1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbGrupo1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 210, 140);

        tbGrupo3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tbGrupo3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Grupo 3", "Pts"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbGrupo3.setSelectionBackground(new java.awt.Color(0, 153, 0));
        tbGrupo3.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tbGrupo3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(280, 60, 210, 140);

        tbGrupo4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tbGrupo4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Grupo 4", "Pts"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbGrupo4.setSelectionBackground(new java.awt.Color(0, 153, 0));
        tbGrupo4.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tbGrupo4);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(280, 230, 210, 160);

        tbGrupo2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tbGrupo2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Grupo 2", "Pts"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbGrupo2.setSelectionBackground(new java.awt.Color(0, 153, 0));
        tbGrupo2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbGrupo2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 230, 210, 160);

        btnArtilheiros.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnArtilheiros.setText("Artilheiros");
        btnArtilheiros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnArtilheiros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArtilheirosActionPerformed(evt);
            }
        });
        getContentPane().add(btnArtilheiros);
        btnArtilheiros.setBounds(120, 420, 87, 23);

        btnPendurados.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnPendurados.setText("Pendurados");
        btnPendurados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPendurados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenduradosActionPerformed(evt);
            }
        });
        getContentPane().add(btnPendurados);
        btnPendurados.setBounds(310, 420, 100, 23);

        btnVoltar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(413, 420, 70, 23);

        btnJogos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnJogos.setText("Jogos");
        btnJogos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJogosActionPerformed(evt);
            }
        });
        getContentPane().add(btnJogos);
        btnJogos.setBounds(20, 420, 90, 23);

        btnSuspensos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSuspensos.setText("Suspensos");
        btnSuspensos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuspensosActionPerformed(evt);
            }
        });
        getContentPane().add(btnSuspensos);
        btnSuspensos.setBounds(210, 420, 97, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/view/7.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
        TelaCarregarCamp telaCarregarCamp = new TelaCarregarCamp();
        telaCarregarCamp.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnArtilheirosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArtilheirosActionPerformed
        this.dispose();
        TelaArtilheiros telaArtilheiros = new TelaArtilheiros(camp); //tem comentário aqui
        telaArtilheiros.setVisible(true);
    }//GEN-LAST:event_btnArtilheirosActionPerformed

    private void btnPenduradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenduradosActionPerformed
        this.dispose();
        TelaPendurados tp = new TelaPendurados(camp); // tem comentário nessa tela
        tp.setVisible(true);
    }//GEN-LAST:event_btnPenduradosActionPerformed

    private void btnJogosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogosActionPerformed
        TelaJogos tj = new TelaJogos(camp);
        tj.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnJogosActionPerformed

    private void btnSuspensosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuspensosActionPerformed
        TelaSuspensos ts = new TelaSuspensos(camp); // e nessa aqui também
        ts.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSuspensosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaQuatroGrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaQuatroGrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaQuatroGrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaQuatroGrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //               new TelaQuatroGrupos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArtilheiros;
    private javax.swing.JButton btnJogos;
    private javax.swing.JButton btnPendurados;
    private javax.swing.JButton btnSuspensos;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tbGrupo1;
    private javax.swing.JTable tbGrupo2;
    private javax.swing.JTable tbGrupo3;
    private javax.swing.JTable tbGrupo4;
    // End of variables declaration//GEN-END:variables
}
