/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model.view;

import java.awt.Image;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.util.List;
import javax.swing.ImageIcon;
import model.bean.Campeonato;
import model.bean.Partida;
import model.dao.PartidaDAO;


/**
 *
 * @author Cliente
 */
public class TelaFinal extends javax.swing.JFrame {
Campeonato camp;
    /**
     * Creates new form TelaFinal
     */
    public TelaFinal(Campeonato camp) {
        initComponents();
        this.camp = camp;
        PartidaDAO partidaDAO = new PartidaDAO();
        List<Partida> partidas = partidaDAO.listarFase(camp, "final");
        byte[] escudo = partidas.get(0).getMandante().getEscudo();
        InputStream is = new ByteArrayInputStream(escudo);
        Image image = new ImageIcon(escudo).getImage();
        ImageIcon icon = new ImageIcon(image);
        lblEscudoTime1.setIcon(icon);
        lblNomeTime1.setText(partidas.get(0).getMandante().getNome());
        escudo = partidas.get(0).getVisitante().getEscudo();
        is = new ByteArrayInputStream(escudo);
        image = new ImageIcon(escudo).getImage();
        icon = new ImageIcon(image);
        lblEscudoTime2.setIcon(icon);
        lblNomeTime2.setText(partidas.get(0).getVisitante().getNome());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNovaPartida = new javax.swing.JButton();
        btnArtilheiros = new javax.swing.JButton();
        btnSuspensos = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblEscudoTime1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblEscudoTime2 = new javax.swing.JLabel();
        lblNomeTime1 = new javax.swing.JLabel();
        lblNomeTime2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Final");
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        btnNovaPartida.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNovaPartida.setText("Jogos");
        btnNovaPartida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNovaPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaPartidaActionPerformed(evt);
            }
        });
        getContentPane().add(btnNovaPartida);
        btnNovaPartida.setBounds(40, 400, 110, 30);

        btnArtilheiros.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnArtilheiros.setText("Artilheiros");
        btnArtilheiros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnArtilheiros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArtilheirosActionPerformed(evt);
            }
        });
        getContentPane().add(btnArtilheiros);
        btnArtilheiros.setBounds(160, 400, 87, 30);

        btnSuspensos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSuspensos.setText("Suspensos");
        btnSuspensos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSuspensos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuspensosActionPerformed(evt);
            }
        });
        getContentPane().add(btnSuspensos);
        btnSuspensos.setBounds(260, 400, 97, 30);

        btnCancelar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(370, 400, 83, 30);

        lblEscudoTime1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblEscudoTime1.setForeground(new java.awt.Color(255, 255, 255));
        lblEscudoTime1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEscudoTime1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        getContentPane().add(lblEscudoTime1);
        lblEscudoTime1.setBounds(30, 140, 190, 160);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 180, 30, 100);

        lblEscudoTime2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblEscudoTime2.setForeground(new java.awt.Color(255, 255, 255));
        lblEscudoTime2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEscudoTime2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        getContentPane().add(lblEscudoTime2);
        lblEscudoTime2.setBounds(290, 140, 190, 160);

        lblNomeTime1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNomeTime1.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeTime1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeTime1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        getContentPane().add(lblNomeTime1);
        lblNomeTime1.setBounds(30, 300, 190, 14);

        lblNomeTime2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNomeTime2.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeTime2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeTime2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        getContentPane().add(lblNomeTime2);
        lblNomeTime2.setBounds(290, 300, 190, 14);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/view/7.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 500, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovaPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaPartidaActionPerformed
        TelaJogos t = new TelaJogos(camp);
        t.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNovaPartidaActionPerformed

    private void btnArtilheirosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArtilheirosActionPerformed
        this.dispose();
        TelaArtilheiros telaArtilheiros = new TelaArtilheiros(camp);
        telaArtilheiros.setVisible(true);
    }//GEN-LAST:event_btnArtilheirosActionPerformed

    private void btnSuspensosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuspensosActionPerformed
        this.dispose();
        TelaSuspensos ts = new TelaSuspensos(camp);
        ts.setVisible(true);
    }//GEN-LAST:event_btnSuspensosActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
        TelaCarregarCamp telaCarregarCamp = new TelaCarregarCamp();
        telaCarregarCamp.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
          //      new TelaFinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArtilheiros;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnNovaPartida;
    private javax.swing.JButton btnSuspensos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblEscudoTime1;
    private javax.swing.JLabel lblEscudoTime2;
    private javax.swing.JLabel lblNomeTime1;
    private javax.swing.JLabel lblNomeTime2;
    // End of variables declaration//GEN-END:variables
}
