/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model.view;


import model.bean.Campeonato;
import model.bean.Jogador;
import model.bean.Resultados;
import model.bean.Time;
import model.dao.ResultadosDAO;


/**
 *
 * @author Cliente
 */
public class TelaPremios extends javax.swing.JFrame {
Campeonato camp;
    /**
     * Creates new form TelaPremios
     */
    public TelaPremios(Campeonato camp) {
        initComponents();
        this.camp=camp;
        Resultados res = new ResultadosDAO().buscar(camp);
        Time campeao = res.getCampeao();
        Time vice = res.getViceCampeao();
        Jogador artilheiro = res.getArtilheiro();
        lblArtilheiro.setText(artilheiro.getApelido());
        lblGols.setText(String.valueOf(artilheiro.getGols()));
        lblCampeao.setText(campeao.getNome());  // coloca o nome do campeão
        lblVice.setText((vice.getNome())); // do vice

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSair = new javax.swing.JButton();
        lblCampeao = new javax.swing.JLabel();
        lblVice = new javax.swing.JLabel();
        lblArtilheiro = new javax.swing.JLabel();
        lblGols = new javax.swing.JLabel();
        btnDados = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Premiação");
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        btnSair.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(375, 433, 70, 30);

        lblCampeao.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblCampeao.setForeground(new java.awt.Color(255, 255, 255));
        lblCampeao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        getContentPane().add(lblCampeao);
        lblCampeao.setBounds(180, 170, 150, 40);

        lblVice.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblVice.setForeground(new java.awt.Color(255, 255, 255));
        lblVice.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        getContentPane().add(lblVice);
        lblVice.setBounds(210, 240, 130, 40);

        lblArtilheiro.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblArtilheiro.setForeground(new java.awt.Color(255, 255, 255));
        lblArtilheiro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        getContentPane().add(lblArtilheiro);
        lblArtilheiro.setBounds(170, 310, 160, 30);

        lblGols.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblGols.setForeground(new java.awt.Color(255, 255, 255));
        lblGols.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGols.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        getContentPane().add(lblGols);
        lblGols.setBounds(320, 370, 40, 30);

        btnDados.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnDados.setText("Jogos");
        btnDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDadosActionPerformed(evt);
            }
        });
        getContentPane().add(btnDados);
        btnDados.setBounds(50, 433, 67, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/view/8.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 500, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        TelaPrincipal tp = new TelaPrincipal();
        tp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDadosActionPerformed
        TelaJogos tj = new TelaJogos(camp);
        tj.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPremios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPremios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPremios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPremios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //           new TelaPremios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDados;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblArtilheiro;
    private javax.swing.JLabel lblCampeao;
    private javax.swing.JLabel lblGols;
    private javax.swing.JLabel lblVice;
    // End of variables declaration//GEN-END:variables
}
