/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model.view;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.bean.Campeonato;
import model.bean.Jogador;
import model.bean.Time;
import model.dao.JogadorDAO;
import model.dao.TimeDAO;

/**
 *
 * @author guilherme
 */
public class TelaArtilheiros extends javax.swing.JFrame {

    Campeonato camp;

    /**
     * Creates new form TelaArtilheiros
     */
    public TelaArtilheiros(Campeonato camp) {
        initComponents();
        this.camp = camp;

        JogadorDAO jogadorDAO = new JogadorDAO();
        DefaultTableModel tbm = (DefaultTableModel) tbArtilheiros.getModel();
        List<Jogador> jogadores = jogadorDAO.listarArtilheiros(camp); // busca os artilheiros por ordem de gols
        for (Jogador jogador : jogadores) {
            tbm.addRow(
                    new Object[]{
                        jogador.getApelido(),
                        jogador.getGols()
                    });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbArtilheiros = new javax.swing.JTable();
        btnVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Artilheiros");
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        tbArtilheiros.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tbArtilheiros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jogador", "Gols"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbArtilheiros.setSelectionBackground(new java.awt.Color(0, 153, 0));
        tbArtilheiros.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbArtilheiros);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 60, 430, 290);

        btnVoltar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(383, 430, 70, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/view/7.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        if (camp.isFaseDeGrupos() == true) {
            if (camp.getNumGrupos() == 2) {
                TelaDoisGrupos tdg = new TelaDoisGrupos(camp);
                tdg.setVisible(true);
            } else if (camp.getNumGrupos() == 4) {
                TelaQuatroGrupos tqg = new TelaQuatroGrupos(camp);
                tqg.setVisible(true);
            }
        } else {
            if (camp.isOitavas()) {
                TelaOitavas t = new TelaOitavas(camp);
                t.setVisible(true);
            } else if (camp.isQuartas()) {
                TelaQuartas t = new TelaQuartas(camp);
                t.setVisible(true);
            } else if (camp.isSemi()) {
                TelaSemi t = new TelaSemi(camp);
                t.setVisible(true);
            } else if (camp.isFinal()) {
                TelaFinal t = new TelaFinal(camp);
                t.setVisible(true);
            }
        }
        this.dispose();

    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaArtilheiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaArtilheiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaArtilheiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaArtilheiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //               new TelaArtilheiros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbArtilheiros;
    // End of variables declaration//GEN-END:variables
}
