/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model.view;

import java.awt.Image;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import model.bean.Campeonato;
import model.bean.Time;
import model.dao.TimeDAO;

/**
 *
 * @author Cliente
 */
public class TelaTimesSemCamp extends javax.swing.JFrame {

    Time time;
    Campeonato camp;
    Icon escudoGenerico;

    /**
     * Creates new form TelaTimesSemCamp
     */
    public TelaTimesSemCamp(Campeonato camp) {
        initComponents();
        this.camp = camp;
        escudoGenerico = lblEscudo.getIcon();
        
        TimeDAO timeDAO = new TimeDAO();
        List<Time> times = timeDAO.listarPorCamp(camp);
        timesC = times.size();
        numTimes = camp.getNumTimes();
        lblTimesCriados.setText(String.valueOf(timesC));
        lblNumTimes.setText(String.valueOf(numTimes));
        
        List<Time> timesSemCamp = timeDAO.listarTimesSemCamp();
        DefaultListModel model = (DefaultListModel)lstTimes.getModel();
        for(Time time:timesSemCamp){
            model.addElement(time);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstTimes = new javax.swing.JList(new DefaultListModel());
        lblEscudo = new javax.swing.JLabel();
        lblDirigente = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblTimesCriados = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblNumTimes = new javax.swing.JLabel();
        ckhCabecaDeChave = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lstTimes.setBackground(new java.awt.Color(126, 217, 87));
        lstTimes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        lstTimes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lstTimes.setForeground(new java.awt.Color(255, 255, 255));
        lstTimes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstTimes.setSelectionBackground(new java.awt.Color(0, 204, 0));
        lstTimes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstTimesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstTimes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 210, 270));

        lblEscudo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEscudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/view/escudoGenerico.png"))); // NOI18N
        jPanel1.add(lblEscudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 140, 160));

        lblDirigente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDirigente.setForeground(new java.awt.Color(255, 255, 255));
        lblDirigente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(lblDirigente, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 130, 20));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cidade:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, 20));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dirigente:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, 20));

        lblCidade.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCidade.setForeground(new java.awt.Color(255, 255, 255));
        lblCidade.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(lblCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 130, 20));

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, -1, 30));

        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setText("Apagar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 90, 30));

        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setText("Adicionar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("N° Times:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, 20));

        lblTimesCriados.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTimesCriados.setForeground(new java.awt.Color(255, 255, 255));
        lblTimesCriados.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(lblTimesCriados, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 20, 20));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("/");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 20, 20));

        lblNumTimes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNumTimes.setForeground(new java.awt.Color(255, 255, 255));
        lblNumTimes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(lblNumTimes, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 20, 20));

        ckhCabecaDeChave.setBackground(new java.awt.Color(126, 217, 87));
        ckhCabecaDeChave.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ckhCabecaDeChave.setForeground(new java.awt.Color(255, 255, 255));
        ckhCabecaDeChave.setText("Cabeça de Chave");
        jPanel1.add(ckhCabecaDeChave, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/view/7.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int timesC;
    int numTimes;
    public void atualizar(){
        TimeDAO timeDAO = new TimeDAO();
        List<Time> times = timeDAO.listarPorCamp(camp);
        timesC = times.size();
        numTimes = camp.getNumTimes();
        lblTimesCriados.setText(String.valueOf(timesC));
        lblNumTimes.setText(String.valueOf(numTimes));
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        TimeDAO timeDAO = new TimeDAO();
        timeDAO.excluir(time);
        DefaultListModel model = (DefaultListModel) lstTimes.getModel();
        model.remove(lstTimes.getSelectedIndex());
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        time.setCampeonato(camp);
        time.setCabecaDeChave(ckhCabecaDeChave.isSelected());
        TimeDAO timeDAO = new TimeDAO();
        timeDAO.adicionarNoCamp(time);
        DefaultListModel model = (DefaultListModel) lstTimes.getModel();
        model.remove(lstTimes.getSelectedIndex());
        lblDirigente.setText("");
        lblCidade.setText("");
        lblEscudo.setIcon(escudoGenerico);
        atualizar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TelaCadastroTime t = new TelaCadastroTime(camp);
        t.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lstTimesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstTimesMouseClicked
        time = (Time) lstTimes.getSelectedValue();
        lblDirigente.setText(time.getDirigente());
        lblCidade.setText(time.getCidade());
        byte[] escudo = time.getEscudo();
        InputStream is = new ByteArrayInputStream(escudo);
        Image image = new ImageIcon(escudo).getImage();
        ImageIcon icon = new ImageIcon(image);
        lblEscudo.setIcon(icon);
    }//GEN-LAST:event_lstTimesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTimesSemCamp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTimesSemCamp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTimesSemCamp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTimesSemCamp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //    new TelaTimesSemCamp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ckhCabecaDeChave;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblDirigente;
    private javax.swing.JLabel lblEscudo;
    private javax.swing.JLabel lblNumTimes;
    private javax.swing.JLabel lblTimesCriados;
    private javax.swing.JList lstTimes;
    // End of variables declaration//GEN-END:variables
}
